[package]
description.workspace = true
edition.workspace = true
license.workspace = true
name = "kittynode-tauri"
publish = false
readme.workspace = true
repository.workspace = true
version = "0.2.0"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "kittynode_tauri_lib"

[build-dependencies]
tauri-build = { version = "2.0.3", features = [] }

[dependencies]
eyre = { version = "0.6.12", default-features = false, features = [
  "auto-install",
  "track-caller",
] }
kittynode-core = { version = "0.4.0", path = "../../core" }
once_cell = "1.20.2"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tauri = { version = "2.1.1", features = ["devtools"] }
tauri-plugin-dialog = "2.0.3"
tauri-plugin-fs = "2.0.3"
tauri-plugin-http = "2.0.3"
tauri-plugin-os = "2.0.1"
tauri-plugin-process = "2.0.1"
tokio = "1.41.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2.0.2"
